name: push

on:
  push:
    branches: [main]

jobs:
  test-build-publish-release:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun check
      - run: bun server:files # Files need to be available for valid types import in test.
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
      - run: bun types
      - run: bun run test:node
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
      # Tests running in parallel and browser environment cannot be torn down properly after tests.
      - run: bun run test:browser
      - uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
