name: push

on:
  push:
    branches: [main]

jobs:
  test-build-publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: 🚧 Build
        run: bun run build
      - name: 🧪 Test
        run: bun test
      - run: npm install -g npm@latest
      - name: 📢 Release
        uses: tobua/release-npm-action@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
