name: push

on:
  push:
    branches: [main]

jobs:
  test-build-publish-release:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: 🚧 Build
        run: bun run build
      - name: 🧪 Test Server
        run: bun run test:node
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # Tests running in parallel and browser environment cannot be torn down properly after tests.
      - name: 🧪 Test Browser
        run: bun run test:browser
      - name: 🛠️ Build Demo
        run: |
          cd demo
          bun install
          bunx papua build
      - name: 🚀 Publish Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: publish
          folder: demo/dist
      - name: 📢 Release
        uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
